import type { Preset } from "./types";

export const PRESETS: Preset[] = [
  {
    id: "expense-form",
    title: "Fill a mock expense form",
    purpose: "Watch the agent fill and submit a multi-field expense report.",
    goal: "Submit an expense report for a $48.20 client lunch on March 12.",
    estSteps: 7,
    quickPrompts: [
      "Submit a $48.20 client lunch expense",
      "File a $120 software subscription expense",
      "Submit a travel expense for $310.55",
      "Reimburse a $22 coffee meeting",
    ],
    steps: [
      {
        id: "s1",
        kind: "plan",
        label: "Plan the form submission",
        explain:
          "Before acting, the agent breaks the goal into smaller steps: open the form, fill each field, attach the receipt, then submit and confirm.",
        reasoning:
          "Sequencing fields top-to-bottom matches how humans complete forms and reduces validation errors.",
        screen: "expense-empty",
      },
      {
        id: "s2",
        kind: "click",
        label: "Open New Expense",
        target: "Button: New Expense",
        explain: "The agent clicks the primary action that opens the empty expense form.",
        observation: "Empty expense form appeared with 5 fields.",
        screen: "expense-empty",
      },
      {
        id: "s3",
        kind: "type",
        label: "Type merchant + amount",
        target: "Fields: Merchant, Amount",
        explain: "The agent types text into recognized input fields.",
        observation: "Merchant set to 'Bistro Lumière'. Amount set to $48.20.",
        screen: "expense-partial",
      },
      {
        id: "s4",
        kind: "type",
        label: "Set date + category",
        target: "Fields: Date, Category",
        explain: "Date pickers and dropdowns are filled by selecting the matching option.",
        observation: "Date 2024-03-12. Category 'Meals & Entertainment'.",
        screen: "expense-filled",
      },
      {
        id: "s5",
        kind: "click",
        label: "Attach receipt",
        target: "Button: Upload receipt",
        explain: "Mock file selected from the desktop. Real systems would open a file dialog.",
        observation: "receipt-2024-03-12.pdf attached (124 KB).",
        screen: "expense-receipt",
      },
      {
        id: "s6",
        kind: "click",
        label: "Submit form",
        target: "Button: Submit",
        explain: "The agent submits the completed form.",
        observation: "Confirmation screen with reference EXP-7741.",
        extracted: { reference: "EXP-7741" },
        screen: "expense-submitted",
      },
      {
        id: "s7",
        kind: "verify",
        label: "Verify submission",
        explain: "Agent re-reads the screen to confirm the success state and capture the ID.",
        observation: "Status: Submitted. Reference EXP-7741 visible.",
        reasoning: "All required fields present + success banner = pass.",
        screen: "expense-submitted",
      },
    ],
    finalExtract: {
      reference: "EXP-7741",
      amount: "$48.20",
      category: "Meals & Entertainment",
    },
    verification: [
      { label: "Form submitted", pass: true, reason: "Success banner detected." },
      { label: "Reference ID captured", pass: true, reason: "EXP-7741 extracted from page." },
      { label: "Receipt attached", pass: true, reason: "File upload confirmed." },
    ],
  },
  {
    id: "invoice-extract",
    title: "Extract invoice details from a fake portal",
    purpose: "Log in to a vendor portal and pull structured invoice fields.",
    goal: "Extract invoice number, date, total, and vendor for the latest invoice.",
    estSteps: 6,
    quickPrompts: [
      "Get the latest invoice details",
      "Find invoices over $1,000 this month",
      "Extract vendor and total only",
      "Pull the most recent 3 invoices",
    ],
    steps: [
      {
        id: "s1",
        kind: "plan",
        label: "Plan extraction",
        explain:
          "The agent decides it needs to log in, navigate to invoices, open the latest, and extract a structured object.",
        reasoning: "Schema-first extraction reduces hallucinated fields.",
        screen: "portal-login",
      },
      {
        id: "s2",
        kind: "type",
        label: "Enter credentials",
        target: "Fields: email, password",
        explain: "Mock credentials are typed into the login form.",
        observation: "Login successful — dashboard loaded.",
        screen: "portal-dashboard",
      },
      {
        id: "s3",
        kind: "click",
        label: "Open Invoices tab",
        target: "Nav: Invoices",
        explain: "The agent navigates by clicking visible navigation labels.",
        observation: "Invoice list with 12 rows visible.",
        screen: "portal-invoices",
      },
      {
        id: "s4",
        kind: "click",
        label: "Open latest invoice",
        target: "Row: INV-2041",
        explain: "The newest invoice (top row) is selected.",
        observation: "Invoice INV-2041 detail page loaded.",
        screen: "portal-invoice-detail",
      },
      {
        id: "s5",
        kind: "extract",
        label: "Extract fields",
        explain: "Structured fields are parsed from the rendered detail view.",
        observation: "All 4 expected fields located.",
        extracted: {
          invoice: "INV-2041",
          date: "2024-03-18",
          total: "$2,480.00",
          vendor: "Northwind Cloud",
        },
        screen: "portal-invoice-detail",
      },
      {
        id: "s6",
        kind: "verify",
        label: "Verify schema",
        explain: "Each extracted field is checked against the expected type and format.",
        reasoning: "All keys present and values match expected formats — pass.",
        screen: "portal-invoice-detail",
      },
    ],
    finalExtract: {
      invoice: "INV-2041",
      date: "2024-03-18",
      total: "$2,480.00",
      vendor: "Northwind Cloud",
    },
    verification: [
      { label: "Invoice number present", pass: true, reason: "Matches /^INV-\\d+$/." },
      { label: "Date is ISO format", pass: true, reason: "2024-03-18 parses cleanly." },
      { label: "Total parses to currency", pass: true, reason: "$2,480.00 → 2480.00 USD." },
      { label: "Vendor non-empty", pass: true, reason: "Northwind Cloud." },
    ],
  },
  {
    id: "helpdesk-ticket",
    title: "File a helpdesk support ticket",
    purpose: "Search the KB then file a structured ticket with category and priority.",
    goal: "File a high-priority ticket about VPN disconnects on macOS.",
    estSteps: 7,
    quickPrompts: [
      "VPN keeps disconnecting on macOS",
      "Email client cannot send attachments",
      "Printer offline in 3rd floor lounge",
      "Need access to shared drive Marketing/Q2",
    ],
    steps: [
      {
        id: "s1",
        kind: "plan",
        label: "Plan the ticket flow",
        explain: "Search KB first to avoid duplicates, then file ticket if no fix is found.",
        reasoning: "KB-first is the policy for new tickets.",
        screen: "helpdesk-home",
      },
      {
        id: "s2",
        kind: "type",
        label: "Search KB for 'VPN macOS'",
        target: "Search box",
        explain: "Looks for an existing article that resolves the issue.",
        observation: "3 articles found — none match macOS Sonoma.",
        screen: "helpdesk-search",
      },
      {
        id: "s3",
        kind: "click",
        label: "Start new ticket",
        target: "Button: New ticket",
        explain: "No KB article applies, so the agent escalates to a ticket.",
        observation: "New ticket form shown.",
        screen: "helpdesk-new",
      },
      {
        id: "s4",
        kind: "type",
        label: "Set category + priority",
        target: "Fields: Category, Priority",
        explain: "Category 'Network' and priority 'High' selected from dropdowns.",
        observation: "Category=Network, Priority=High.",
        screen: "helpdesk-new",
      },
      {
        id: "s5",
        kind: "type",
        label: "Type description",
        target: "Field: Description",
        explain: "Concise repro steps and environment details typed into the description box.",
        observation: "Description (212 chars) added.",
        screen: "helpdesk-filled",
      },
      {
        id: "s6",
        kind: "click",
        label: "Submit ticket",
        target: "Button: Submit ticket",
        explain: "The agent submits and waits for a ticket ID to be issued.",
        observation: "Ticket TKT-30219 created.",
        extracted: { ticket: "TKT-30219" },
        screen: "helpdesk-submitted",
      },
      {
        id: "s7",
        kind: "verify",
        label: "Verify ticket created",
        explain: "Reads back the success page to confirm the ticket exists.",
        reasoning: "ID present and matches /^TKT-\\d+$/ — pass.",
        screen: "helpdesk-submitted",
      },
    ],
    finalExtract: { ticket: "TKT-30219", category: "Network", priority: "High" },
    verification: [
      { label: "KB checked first", pass: true, reason: "Search executed; no match." },
      { label: "Ticket created", pass: true, reason: "TKT-30219 returned." },
      { label: "Priority correct", pass: true, reason: "High set as required." },
    ],
  },
  {
    id: "qa-flow",
    title: "Run a QA flow on a sample web app",
    purpose: "Execute three smoke checks and produce a pass/fail report.",
    goal: "Verify login, search, and checkout total on the sample shop.",
    estSteps: 7,
    quickPrompts: [
      "Run smoke tests on the shop",
      "Check checkout total math",
      "Verify login + search only",
      "Re-run failed checks",
    ],
    steps: [
      {
        id: "s1",
        kind: "plan",
        label: "Plan QA checks",
        explain: "Three independent checks: login, search, checkout total.",
        reasoning: "Each check is isolated so one failure does not block the others.",
        screen: "qa-home",
      },
      {
        id: "s2",
        kind: "type",
        label: "Login as test user",
        target: "Fields: email, password",
        explain: "Standard login with QA credentials.",
        observation: "Logged in as qa@test.io.",
        screen: "qa-login",
      },
      {
        id: "s3",
        kind: "verify",
        label: "Check #1: login works",
        explain: "Confirms the dashboard greets the user by name.",
        observation: "'Welcome, QA' visible.",
        extracted: { check_login: "pass" },
        screen: "qa-dashboard",
      },
      {
        id: "s4",
        kind: "type",
        label: "Search for 'lamp'",
        target: "Search box",
        explain: "Searches the catalog and counts results.",
        observation: "12 results returned for 'lamp'.",
        extracted: { check_search: "pass" },
        screen: "qa-search",
      },
      {
        id: "s5",
        kind: "click",
        label: "Add to cart + open checkout",
        target: "Button: Add to cart",
        explain: "Adds 2 items and opens the checkout view.",
        observation: "Subtotal $58.00, tax $4.64, total $62.64.",
        screen: "qa-checkout",
      },
      {
        id: "s6",
        kind: "verify",
        label: "Check #3: checkout total math",
        explain: "Recomputes 58 + 4.64 = 62.64 to validate the displayed total.",
        reasoning: "Computed total matches displayed total — pass.",
        extracted: { check_checkout: "pass" },
        screen: "qa-checkout",
      },
      {
        id: "s7",
        kind: "extract",
        label: "Compile report",
        explain: "Aggregates all three checks into a final report object.",
        observation: "3/3 checks passed.",
        screen: "qa-report",
      },
    ],
    finalExtract: {
      check_login: "pass",
      check_search: "pass",
      check_checkout: "pass",
      summary: "3/3 passed",
    },
    verification: [
      { label: "Login check", pass: true, reason: "Welcome banner detected." },
      { label: "Search check", pass: true, reason: "12 results > 0." },
      { label: "Checkout total", pass: true, reason: "58 + 4.64 = 62.64." },
    ],
  },
];

export function getPreset(id: string) {
  return PRESETS.find((p) => p.id === id) ?? PRESETS[0];
}